language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_install:
- PYTHON_MAJOR_VERSION=`echo $TRAVIS_PYTHON_VERSION | head -c 1`
- if [[ $PYTHON_MAJOR_VERSION == 3 ]]; then sudo apt-get install python3-pip; fi
install:
- if [[ $PYTHON_MAJOR_VERSION == 2 ]]; then virtualenv venv; fi
- if [[ $PYTHON_MAJOR_VERSION == 3 ]]; then virtualenv -p python3 venv; fi
- source venv/bin/activate
- if [[ $PYTHON_MAJOR_VERSION == 2 ]]; then pip  install -e .; pip install numpy pytest; fi
- if [[ $PYTHON_MAJOR_VERSION == 3 ]]; then pip3 install -e .; pip3 install numpy pytest; fi
- if [[ $PYTHON_MAJOR_VERSION == 2 ]]; then python  setup.py develop; fi
- if [[ $PYTHON_MAJOR_VERSION == 3 ]]; then python3 setup.py develop; fi
script:
- if [[ $PYTHON_MAJOR_VERSION == 2 ]]; then python  -m pytest -v -x test.py; fi
- if [[ $PYTHON_MAJOR_VERSION == 3 ]]; then python3 -m pytest -v -x test.py; fi
